apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30339
  selector:
    app: gitea
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-pv-volume
  labels:
    app: gitea
    type: local
spec:
  storageClassName: gitea
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/gitea"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pv-claim
  labels:
    app: gitea
spec:
  storageClassName: gitea
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  selector:
    matchLabels:
      app: gitea
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitea
    spec:
      initContainers:
        - name: init-setup-db
          image: mysql:5.7
          env:
          - name: GITEA_DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-gitea-secret
                key: username
          - name: GITEA_DB_PASS
            valueFrom:
              secretKeyRef:
                name: mysql-gitea-secret
                key: password
          command:
            - "/bin/sh"
            - "-c"
            - "until mysql --host=mysql.default --user=$GITEA_DB_USER --password=$GITEA_DB_PASS --execute=\"SELECT 1;\"; do echo waiting for mysql; sleep 2; done;" 
      containers:
      - image: tsilyk/gitea-server:latest
        name: gitea
        env:
        - name: GITEA__database__DB_TYPE
          value: mysql
        - name: GITEA__database__HOST
          value: mysql:3306
        - name: GITEA__database__NAME
          value: gitea_db
        - name: GITEA__database__USER
          valueFrom:
            secretKeyRef:
              name: mysql-gitea-secret
              key: username
        - name: GITEA__database__PASSWD
          valueFrom:
            secretKeyRef:
              name: mysql-gitea-secret
              key: password
        - name: GITEA__server__ROOT_URL
          value: http://softserve.eq.org.ua:30339/
        - name: GITEA__server__LFS_JWT_SECRET
          value: eqiu-ihY3KO0Uwz6MhYxagzAcABn01RR6TMyWMMdmog
        - name: GITEA__server__DISABLE_SSH 
          value: "true"
        - name: GITEA__security__INTERNAL_TOKEN
          value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2NzQ3Nzc3MjZ9.oI_kLfUUnQaJZJiwTIAF0BQmNg92CkFe-E6QVSkGJEw
        - name: GITEA__openid__ENABLE_OPENID_SIGNIN
          value: "false"
        - name: GITEA__openid__ENABLE_OPENID_SIGNUP 
          value: "false"
        - name: GITEA__security__INSTALL_LOCK
          value: "false"
        ports:
        - containerPort: 3000
          name: gitea
        volumeMounts:
        - name: gitea-persistent-storage
          mountPath: /va/lib/gitea
      volumes:
      - name: gitea-persistent-storage
        persistentVolumeClaim:
          claimName: gitea-pv-claim
