apiVersion: v1
kind: Secret
metadata:
  name: mysql-gitea-secret
type: Opaque
data:
  # encrypted with echo -n ‘value’ | base64
  username: Z2l0ZWE=
  password: Z2l0ZWEx
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-secret
type: Opaque
data:
  # encrypted with echo -n ‘value’ | base64
  password: cGFzc3dvcmQ=

